server:
  port: 8083
spring:
  config:
    name: custom


#person:
#  name: jq
#  age: 10
#  sex: sd
#yaml-person:
#  name: jq
#  age: 10
#  sex: nv
app:
  id: 111
  na-m_e: yml222
  desc: ${app.name}描述
  titles:
    - yml1
    - yml2


#spring:
#  autoconfigure:
#    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration


#spring:
#  banner:
#    location: classpath:/banner1/banner.txt
#    image:
#      location: classpath:/banner.png
#spring:
#  main:
#    banner-mode: console